### ISSUE TITLE
Table cells do not allow <br/> elements

### ISSUE THREAD

**Issue by profnimrod** [Annotum/Annotum#222] opened 2015-01-02 14:27 UTC
The table editor seems to remove any carriage returns, or <br/> elements inserted making it difficult to create cells with multiple paragraphs.  Italicization and emboldening is also blocked.

**Comment by profnimrod** [comment] 2015-01-11 21:13
Just to confirm: http://dtd.nlm.nih.gov/ncbi/kipling/doc/td.html indicates that <td> tags are allowed <br/> tags as children.

**Comment by carlthewebmaster** [comment] 2015-01-11 21:27
Duplicate of #214

**Closed by carlthewebmaster** 2015-01-11 21:27 UTC
